# Generated by Django 6.0.4 on 2026-05-01 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_chatmessage_chatsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionchatconversation',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admissionchatconversation',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
